-- ==========================================
-- VocalVault: Supabase PostgreSQL Schema
-- ==========================================
-- Run this script in the Supabase SQL Editor
-- (Dashboard -> SQL Editor -> New Query -> Run)

-- 1. Create Users Table
CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    password_hash TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. Create Songs Table
CREATE TABLE IF NOT EXISTS songs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
    song_name VARCHAR(255) NOT NULL,
    artist VARCHAR(255) NOT NULL,
    language VARCHAR(100) NOT NULL,
    difficulty VARCHAR(50) NOT NULL, -- 'Easy', 'Medium', 'Hard'
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. Create Practice Table
CREATE TABLE IF NOT EXISTS practice (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
    song_id BIGINT REFERENCES songs(id) ON DELETE CASCADE,
    date DATE NOT NULL DEFAULT CURRENT_DATE,
    minutes INTEGER NOT NULL,
    rating INTEGER CHECK (rating >= 1 AND rating <= 5),
    notes TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Disable Row Level Security (RLS) for simple backend API access
-- This ensures the Flask backend can query and insert records without policy restrictions
ALTER TABLE IF EXISTS users DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS songs DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS practice DISABLE ROW LEVEL SECURITY;
